### ISSUE TITLE
主题监听&切换方案

### ISSUE THREAD

**Issue by lqcool** [lqcool/blog#2]
# 页面换肤

在研发中会遇到支持不同的颜色模式的需求，常见的就是浅色模式和深色模式支持。

## 方法一：JS脚本监听当前的系统设置的模式

通过脚本监听，然后可以动态设置浅色和深色模式的顶级class，比如浅色模式顶级容器对应的class叫light_theme，深色模式对应的顶级容器class为dark_theme，那么可以通过脚本判断当前的系统设置的模式，然后动态切换class。这种换主题方案需要三步，第一需要针对深色&暗色模式定义两个不同的class，然后每个class下面通过css variable 定义颜色值。第二就是通过监听系统设置，动态切换class。第三，就是使用class。

第一步：
```css
// 通用的一些变量，不区分主题

:root {
  // 基础色
  --color-primary: #fe2c55; // 品牌红色
  --color-primary-2: rgba(254,44,85,.34);
  --color-success: #13c15a; // success

  // 填充色
  --color-primary-fill: var(--color-primary);
  --color-primary-2-fill: var(--color-primary-2);
}

:root .light_theme {
    --color-bg-1: #fff; // 亮色主要背景色
    --color-bg-2: rgba(22, 24, 35, .03);
    --text-color-1: #161823;
}

:root .dark_theme {
    --color-bg-1: #2a2c38; // 暗色主要背景色
    --color-bg-2: rgba(255, 255, 255, .03);
    --text-color-1: #fff;
}

```
第二步：监听主题，切换class，下面是封装的一个hooks。
```javascript
/*
 * @Author: lqcool
 * @Description: 主题切换监听hooks
 */
import { useEffect, useState } from 'react';

enum Theme {
  DarkTheme = 'dark_theme',
  LightTheme = 'light_theme',
}

/**
 *  根据当前用户的设置返回主题（亮色或者暗色主题）
 * @returns light_theme or dark_theme
 */
const useTheme = (): Theme => {
  const [theme, setTheme] = useState<Theme>(Theme.LightTheme);

  useEffect(() => {
    const switchThemeHandler = (e: MediaQueryListEvent): void => {
      if (e.matches) {
        setTheme(Theme.DarkTheme);
      } else {
        setTheme(Theme.LightTheme);
      }
    };

    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', switchThemeHandler);
    return (): void => {
      window.matchMedia('(prefers-color-scheme: dark)').removeEventListener('change', switchThemeHandler);
    };
  }, []);

  return theme;
};

export default useTheme;

```
第三步，使用class
```javascript
import React from 'react';
export default function Welcome(): React.ReactElement {
  const theme = useTheme();
  return (
     <div className={theme}><div/>
  )
}
```

## 方法二：通过媒体查询方式监听当前系统设置模式
具体监听的媒体属性是 prefers-color-scheme，其值可能有 no-preference 表示系统未得知用户在这方面的选项，light 表示用户已告知系统他们选择使用浅色主题的界面。dark 表示用户已告知系统他们选择使用暗色主题的界面。具体实践分为两步，第一就是在顶层通过 class 或者attribute设置浅色或者暗色使用的标志位，其实也是相当于给浅色和深色模式定义了独特的类名或者属性，方便css选择器定位。这里就以自定义标签属性方式来做，我们在根元素设置浅色和深色的使用的属性以及属性名。第二步就是通过媒体查询监听当前用户设置的模式，然后通过css 属性选择器来定义两套不同的颜色。

第一步：在html根元素上定义浅色和深色模式对应的属性和属性值，方便后面写媒体查询的时候，用属性选择器选择不同的主题。
```html
<!DOCTYPE html>
<html lang="zh-cn" data-light-theme="light" data-dark-theme="dark">
<head>
    <meta charset="utf-8">
    <title>Growth</title>
    <meta name="screen-orientation" content="portrait">
    <meta name="x5-orientation" content="portrait">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimum-scale=1, maximum-scale=1, minimal-ui, viewport-fit=cover">
    <meta name="apple-mobile-web-app-capable" content="yes">
</head>
<body>
    <div id="root"></div>
</body>
</html>
```

第二步：通过css媒体查询 + 属性选择器来匹配不同的主题色。
```css

// 通用的一些变量，不区分主题

:root {
  // 基础色
  --color-primary: #fe2c55; // 品牌红色
  --color-primary-2: rgba(254,44,85,.34);
  --color-success: #13c15a; // success

  // 填充色
  --color-primary-fill: var(--color-primary);
  --color-primary-2-fill: var(--color-primary-2);
}

// 亮色主题
@media(prefers-color-scheme: light) {

  [data-light-theme="light"] {
    --color-bg-1: #fff; // 亮色主要背景色
    --color-bg-2: rgba(22, 24, 35, .03);
    --color-bg-3: #f8f8f8;
    --color-bg-4: rgba(22, 24, 35, .05);

    --text-color-1: #161823;
    --text-color-2: rgba(22, 24, 35, .9);
    --text-color-3: rgba(22, 24, 35, .75);
    --text-color-4: rgba(22, 24, 35, .6);
    --text-color-5: rgba(22, 24, 35, .34);

    --box-shadow-1: 0 -60px 100px rgba(25, 33, 97, .02);
  }
}

// 暗色主题
@media(prefers-color-scheme: dark) {

  [data-dark-theme="dark"] {
    --color-bg-1: #2a2c38; // 暗色主要背景色
    --color-bg-2: rgba(255, 255, 255, .03);
    --color-bg-3: #1d1f2a;
    --color-bg-4: rgba(255, 255, 255, .06);

    --text-color-1: #fff;
    --text-color-2: rgba(255, 255, 255, .9);
    --text-color-3: rgba(255, 255, 255, .75);
    --text-color-4: rgba(255, 255, 255, .5);
    --text-color-5: rgba(255, 255, 255, .34);

    --box-shadow-1: 0 4px 4px rgba(22, 24, 35, .25);
  }
}
```
